@startuml
skinparam linetype ortho

class Recipe {
    id: Long
    name: String
    author: String
    mealType: MealType
    instructions: String
}

enum MealType {
    STARTER
    ENTREE
    DESSERT
}

class Ingredient {
    id: Long
    name: String
    description: String
}

class Image {
   id: Long
   imgInByte: byte[]
}

class Menu {
    id: Long
    name: String
    starter: Recipe
    entree: Recipe
    dessert: Recipe
}

class RecipeIngredient {
    id: Long
    amount: int
    unit: String
    calories: int
}

Recipe "*" - "*" Ingredient : has
(Recipe, Ingredient) .. RecipeIngredient


Menu  -right->  Recipe
Menu  -right->  Recipe
Menu  -right->  Recipe
Recipe "*" -down-> "1" MealType : is a
Recipe "1" -up-> "1" Image : has
@enduml